
# Server configuration
server:
  port: 9081 #set your port

# Spring Boot configuration
spring:
  application:
    name : item-application
  profiles:
    active: development
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/item_db
    username: admin
    password: secret

  # JPA properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true

