version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: item_db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "9080:80"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge